#!/usr/bin/env bash

# compiles benchmark and run switch converter and instruction namer on it

file="$1"
ext="${file##*\.}"

clang_out=${file/.$ext/.ll}

echo "output to:" $clang_out

include_path="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"

#clang -g -I $include_path -c -emit-llvm -S $file -o $clang_out
if [[ $file == *.c ]]
then
  clang -O0 -I $include_path -I../headers -c -emit-llvm -S $file -o $clang_out
elif [[ $file == *.cc || $file == *.cpp ]]
then
  clang++ -std=c++17 -O0 -I $include_path -I../headers -c -emit-llvm -S $file -o $clang_out
else
  # Ensure that LLVM_CONFIG_PATH
  rustc --crate-type=lib --emit=llvm-ir $file -o $clang_out
fi

#opt -lowerswitch -instnamer -S $clang_out > tmp.ll
opt -load ../llvm-pass/build/addEmptyBlocks/libAddEmptyBlocksPass.so -addEmptyBlock -lowerinvoke --unreachableblockelim -instnamer -S $clang_out > tmp.ll

mv tmp.ll $clang_out

loops_out=${file/.$ext/.loops}
echo "output loops info to:" $loops_out
# TODO: re-add -analyze flag using -passes
opt -loops $clang_out > $loops_out
